---

  - name: Write swapfile
    command: dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }} creates={{ swapfile_location }}
    register: write_swapfile
    become: yes

  - name: Set swapfile permissions
    file: path={{ swapfile_location }} mode=0600
    become: yes

  - name: "Check swap file type"
    command: file {{ swapfile_location }}
    register: swapfile
    become: yes

  - name: Make swap file
    command: mkswap {{ swapfile_location }}
    when: swapfile.stdout.find('swap file') == -1
    register: mkswap
    become: yes

  - name: Check swap enabled
    command: swapon -s
    register: swapon
    become: yes

  - name: Enable swapfile
    command: swapon {{ swapfile_location }}
    when: swapon.stdout.find('{{ swapfile_location }}') == -1
    become: yes

  - name: Write swap entry in fstab
    mount: name=none src={{ swapfile_location }} fstype=swap opts=sw passno=0 dump=0 state=present
    become: yes
